package darkRealm;

import java.util.HashMap;

public class FindDifference {

//  389. Find the Difference
//  Given two strings s and t which consist of only lowercase letters.
//
//  String t is generated by random shuffling string s and then add one more letter at a random position.
//
//  Find the letter that was added in t.
//
//  Example:
//
//  Input:
//  s = "abcd"
//  t = "abcde"
//
//  Output:
//  e
//
//  Explanation:
//      'e' is the letter that was added.

  public static char findTheDifference(String s, String t) {
    int sum = 0;
    for (char c : t.toCharArray())
      sum += (int) c;

    for (char c : s.toCharArray())
      sum -= (int) c;

    return (char) sum;
  }

  public static char findTheDifferenceOLD(String s, String t) {
    HashMap<Character, Integer> map = new HashMap<>();
    for (int i = 0; i < s.length(); i++)
      map.put(s.charAt(i), map.getOrDefault(s.charAt(i), 0) + 1);
    for (int i = 0; i < t.length(); i++) {
      if (map.containsKey(t.charAt(i))) {
        if (map.get(t.charAt(i)) == 1)
          map.remove(t.charAt(i));
        else
          map.put(t.charAt(i), map.get(t.charAt(i)) - 1);
      } else return t.charAt(i);
    }
    return (Character) map.keySet().toArray()[0];
  }

  public static void main(String[] args) {
//    String s = "abcd";
//    String t = "abcde";

    String s = "aa";
    String t = "aaa";

    char c = findTheDifference(s, t);
    System.out.println("s : " + s + "\nt : " + t + "\nc : " + c);
  }
}
